### ISSUE TITLE
Resume/Quit Menu nonfuntional

### ISSUE THREAD

**Issue by nevzheng** [evanbowman/Blind-Jump#10]
in game, upon hitting escape, the resume and quit are not clickable and don't do anything.

**Comment by evanbowman** [comment]
Escape quits the menu, the arrow keys and z select the menu options. They just aren't animated yet so you can't see it happening. Editing the code to add this seemingly simple feature is a huge time commitment. Basically I would want the text to grow or change color when selected. The game's logic thread normally handles state changes like this, but modifying text needs to happen exclusively on the main thread (required by macOS). 
As a result the UI code has grown into a tangled nightmare because of the complex messaging between threads, and knowing how messy it'll be to fix this I've been procrastinating.

**Comment by nevzheng** [comment]
No animation is fine, but maybe you could write some instructions

**Comment by evanbowman** [comment]
Nah I really should fix it, I'll get around to it soon

**Comment by evanbowman** [comment]
Should be fixed now.
