### ISSUE TITLE
What is the folder "resources/"

### ISSUE THREAD

**Issue by tleger1958** [evanbowman/Blind-Jump#13]
Hello,

In many files, there is the folder "resources/". But I cant' find it!

Has it been deleted?

**Comment by evanbowman** [comment]
Are you using MacOS? For the MacOS builds, the resource loading looks into a folder in the .app package bundle called resources: https://github.com/evanbowman/blind-jump/blob/c59a891f36ff1025be4ed10fa519824ea6e4e417/src/ResourcePath.cpp#L24

The cmake script is supposed to create the bundled resources directory here: https://github.com/evanbowman/blind-jump/blob/master/build/CMakeLists.txt#L34

The file hasn't been deleted though, should be in res/music

I would almost suggest that, if CLion is having trouble creating an app bundle, you could hard-code the resource path, but another issue you might run into is that the program linker _also_ looks for the SFML frameworks in the app bundle https://github.com/evanbowman/blind-jump/blob/master/build/CMakeLists.txt#L31

The mac build is really only designed to be run as an app bundle. Haha if this isn't your issue sorry for going off on a long tangent

**Comment by tleger1958** [comment]
Hello,

No, I'm not on MacOs, I'm on Debian.

So, I tried to compile from source the version given here: https://github.com/evanbowman/blind-jump/releases

During execution, it gives me this:"... /share/blindjump/teleporterBeamGlow. png". Reason: Unable to open file

Indeed, there is no "share/" folder for me!

And, for the current version, I have some problems too.

I did without Clion, and I followed README's instructions.

I downloaded the project with "git clone", and I did "cmake. && make", and I got the same mistakes as with Clion :
-Code problems can only be solved with the addition of -fpermissive to CMakeLists. txt.
-Unable to link SFML

If I fix the SFML problems by adding FindSFML.cmake , and if I can run the program, I see some references to folder I can’t find. That is the same problem as with the version here: https://github.com/evanbowman/blind-jump/releases. Then there is no texture, and I hear the character's movements and the background music, but I don't see anything, just black, and text in the top left and right. If I press Escape, I can Resume or Quit, but the two options doens’t make anything. I can’t leave the game, only with CTRL+ESC. That's the situation.

I have this messages in the console when the game is running:
`Failed to create texture, invalid size (0x0)

Impossible to create render texture (failed to create the target texture)`

I think it's because texture files (in the famous "resources/" folder) are not found by the program because the "resources/" folder doesn't exist.

I really don't understand. What is this folder ’ressources/’ ? On Linux, how it is created?
Thank you for your time.

**Comment by evanbowman** [comment]
Ah, actually I've seen the `Failed to create texture, invalid size (0x0)` error before, a few months ago someone else had this same problem.

One possibility is that your screen resolution isn't supported by default, and as a result the code that tries to lookup a resolution for your screen's aspect ratio fails and is using 0x0 as a size to create rendering target. Can you check the configuration file and see if you can find your screen's aspect ratio? https://github.com/evanbowman/blind-jump/blob/master/res/config.json#L2

If the aspect ratio is missing, can you add a new one for your display? The game renders to a smaller resolution and upsamples to create the pixelated look, so don't use your exact resolution, pick some smaller parameters that match your aspect ratio and have a similar area to the other settings that you see in the configuration file. I can recommend width and height values too if you tell me your aspect ratio.

If your aspect ratio is indeed missing from the config file, can you create a pull request in order to contribute your added settings to the repository?

Because this issue keeps happening and confusing people, I will make failed aspect ratio lookup a fatal error with a helpful error message.

**Comment by evanbowman** [comment]
Let me know if that helps, and sorry for all the problems, I developed the game on MacOS / Windows and didn't do much testing on linux because I don't have a Linux machine set up to test code on

**Comment by tleger1958** [comment]
My resolution is 1366x768.

I added my resolution in the json file, and **it’s work!**

I will make a push request.

Thank you for your help.

**Comment by tleger1958** [comment]
Oh ok, I have read the code, and indeed the folder "Resources" is for MacOs.

I understand now...
