### ISSUE TITLE
Crashing on levels.

### ISSUE THREAD

**Issue by gabe56f** [evanbowman/Blind-Jump#15]
It has some  vector related errors. It's different for VS2017 and VS2015. Should I try exporting using VS2013?

**Comment by gabe56f** [comment]
Using VS2015:
Errors I managed to find: 
enemy.cpp, Line 14 - Vector iterators incompatible (Unhandled exception at 0x5C4EE636 (ucrtbased.dll) in BlindJump.exe: An invalid parameter was passed to a function that considers invalid parameters fatal.)

critter.cpp, Line 123 - another vector related problem

**Comment by gabe56f** [comment]
It could be fixed, by 'commenting' both of the problematic parts, but the first one would cancel the enemy's collision detection. A possible solution to the 1st one, store a copy of the vector, you want to iterate.

The 2nd one is almost unnoticeable when 'commented'.

**Comment by gabe56f** [comment]
**the 2nd one is a little bit noticeable after some time. It is responsible for the rotation while shooting. I should look into fixing that...

**Comment by evanbowman** [comment]
Hi, I've never seen that error before, it looks unusual... at first I wondered if this is a thread synchronization bug, where another thread caused a resize _while_ the enemy/critter code was iterating over the vector, thus invalidating the iterators. I have to get familiar with the code again, I haven't looked at it in a while, but I think that the thread that updates the game logic is the only thing that mutates state, while the graphics loop just draws stuff. If this isn't a threading problem, I'm confused about how the iterators would have become incompatible, since it's iterating over a reference-to-const via a range based loop. I don't have visual studio at the moment, but I'll take a second look at the code that modifies the vector, to see if anything would put it into an undefined state.

**Comment by evanbowman** [comment]
Aha, so it turns out that this may be a thread synchronization issue. Game::nextLevel(), which repopulates the wall vector, is called from the main thread, while the code that checks collisions with the walls runs on a separate thread.

Looking back, now that I know better, I shouldn't have set it up this way. One thing that you could try, is to protect the code that's potentially under contention by adding a mutex to the `Game` class. You would want to acquire the mutex with a lock_guard at the beginning of the `Game::updateLogic` function, and also at the beginning of `Game::nextLevel`

EDIT: 
P.S:
Some more explanation for why the level transition code is organized the way that it is:

Ideally, nextLevel would be called by the logic thread, but creating a new level involves manipulating graphics resources (which *must* be done on the main thread for some operating systems), so it's not clear which thread's responsibility performing the update should be, and dividing the level transition across threads would be tricky

**Comment by gabe56f** [comment]
That explains it. At the first error I already kinda fixed the issue. The issue (that's like really noticeable) is that those orange little monsters (i don't know their names, didn't look into it that much), cause most of the errors, and if you try to fix some of the problems, they will always have another one. The one that I am currently stuck at is their AI, and their Collision Detection ignores the walls. Every other creature is aware of that wall but the little orange one. It's like his AI screwed up a little bit while fixing the other problems.

Another thing is, when exporting with VS2015_XP you freeze a lot of times, instead of crashing. That kinda fixed the issue, and I was able to play 2 levels until the vectors started panicking again.

I am a beginner in C++ SFML, that's how I came across this open-source game. I know the basics of C++, and some of SFML too, that's why I always try to go for the simple way. I might just try a little more advanced stuff so I can improve, but I am saving it for the next time. The way I solved the first problem was by just saving a copy of the vector walls `const std::vector<wall> walls = w;` , instead of direct feeding it into the iteration. This fixed the issue most of the time, but still not perfect. Could improve on it, but I don't know how. That's why I am limited to this problem.

I still don't really understand threads so the last sentence you said was absolute chinese to me.

ps: I really like these type of people, who don't make absolute sh*t for newbies to learn from. They won't really learn anything they will just become worse than ever. Thanks for being such a good guy and sharing the source of your games. Flight is awesome as it is, but you could expand it if you wanted to (it's not needed, it's already a really good 'game').

**Comment by gabe56f** [comment]
Also I respect you for keeping the issues section fresh.

**Comment by gabe56f** [comment]
I might ask too much but regarding the game, there's a high demand (from me of course), for mouse controls it's left really untouched the whole game, you don't really use it for anything. That could be just maybe for shooting and interacting. But the way you made the input handling is good as it is, however it could be made better by a person with better knowledge than me (ie. you, not saying you should do it, but it would help some people).

**Comment by gabe56f** [comment]
If you have a discord would you mind if I would add you? If not no problem, and thanks for replying, if Yes, still thanks for replying (and for sharing your discord).

**Comment by evanbowman** [comment]
I may have fixed the level transition crashes. I can't be sure, because I was never able to reproduce the problem. This commit: https://github.com/evanbowman/blind-jump/commit/14a4a7ebe253164552e755b3aa02cc6fba4662a7 should resolve any threading issues (if threading issues were actually the problem).

**Comment by gabe56f** [comment]
Regarding this, I just found out, that somewhere in the code, the path gets nulled, so the path is completely clear. You COULD add a check to see if path is not empty(), otherwise, the vector can't have vector::back(). This fixed the problems for me, and should aid the problem!
