### ISSUE TITLE
Building From Source Improvment

### ISSUE THREAD

**Issue by nevzheng** [evanbowman/Blind-Jump#6]
System:
MacbookPro Retina macOS 10.12.13
Issue:
Cloned blind-jump repo 
Ran suggested procedure
Didn't have SFML
Cloned SFML source code
did make, make install on SFML
blind jump repo does not link properly to sfml
Tried using the FindSFML.cmake script:
https://github.com/SFML/SFML/blob/master/cmake/Modules/FindSFML.cmake
Put in the build directory, ran cmake and build worked great! linked properly, ran well
![image](https://cloud.githubusercontent.com/assets/6531363/23389508/5c8986cc-fd36-11e6-8257-7ece2bf8679f.png)

Proposed Change:
Add FindSFML.cmake to build dir

**Comment by evanbowman** [comment]
Hey, thanks for the suggestion!
The build system does currently work, only it expects you to first build SFML in deps, because that's where it looks for the frameworks when constructing the BlindJump.app package.
I should put a comment in the readme.

I actually know about the find sfml CMake module, and used to use it. The reason I don't anymore is because using it breaks windows builds, because Windows doesn't have a lib dir so you just have to hope people put SFML in a place where the CMake script can find it. It's easier for me to just say build sfml first, then build BlindJump, then the steps are the same for all operating systems.

**Comment by nevzheng** [comment]
Oh! I get it now!

**Comment by evanbowman** [comment]
Great!

P.S. Btw a lot of the code in this repo is clean, but I also wrote a lot of it two years ago when I was still learning and there's some sloppy stuff in here. I just mean not all of it is a model for good C++ code.

**Comment by nevzheng** [comment]
Understood
